### ISSUE TITLE
SQL coding style - Indentation

### ISSUE THREAD

**Issue by purnendudash** [ispringsolutions/moodle-mod_ispring#11]
Sql statement should follow this indentation style - https://moodledev.io/general/development/policies/codingstyle/sql#indentation

https://github.com/ispringsolutions/moodle-mod_ispring/blob/c4b32f7207a1b39c924c33ab29ed07671ed7a4bd/classes/upgrade/upgrade_db_manager.php#L277

**Comment by Andreanapolicy** [comment]
Hi, @purnendudash
Fixed in #12
