### ISSUE TITLE
upload zip archive

### ISSUE THREAD

**Issue by DushinSlavik** [ispringsolutions/moodle-mod_ispring#16]
Добрый день! Вот такая ошибка при загрузке архива (iSpring+QuizMaker: Scorm 1.2)): Исключение - No description file

Good day! Here is the error when loading the archive (iSpring+QuizMaker: Scorm 1.2)): Exception - - No description file

[Moodle 4.4.2 (Build: 20240812)]

**Comment by Andreanapolicy** [comment]
Hello!
Thank you for your interest in our plugin!
We are already preparing an official release of the product to support the plugin!
We will inform when the release will be :)

Best Regards,
Andrey Dudin
