### ISSUE TITLE
PHP 8.1 is required for using Enumeration

### ISSUE THREAD

**Issue by alex-taiwan-chiou** [ispringsolutions/moodle-mod_ispring#3]
in the mod_form.php , a static class of Enum is required for grading_options
However, Enumeration is a new feature started from PHP 8.1.
But the required version of Moodle 4.1 for this plugin might be installed PHP 8.0
there is a runtime error occurred while adding new activity module of this "iSpring" plugin.
![iSpring_Plugin_bug_report_20240111_alex_chiou](https://github.com/ispringsolutions/moodle-mod_ispring/assets/41117901/de52cd94-c6af-41f1-84e6-308c3575d546)

**Comment by Andreanapolicy** [comment]
Hello @alex-taiwan-chiou. Thanks for issue. 
In the new version 1.2.0 we have fixed this.
Check out this PR https://github.com/ispringsolutions/moodle-mod_ispring/pull/6
